# Generated by Django 5.2.1 on 2026-06-06 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_studygroup_user_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studygroup',
            name='group_code',
            field=models.CharField(max_length=20, unique=True, verbose_name='Код группы (ID)'),
        ),
    ]
