# Generated by Django 5.2.1 on 2026-06-06 15:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_studygroup_group_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='group',
            field=models.ForeignKey(blank=True, help_text='Оставьте пустым, если тест доступен всем', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.studygroup', verbose_name='Учебная группа'),
        ),
    ]
