# Generated by Django 5.2.1 on 2026-06-07 17:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_testresult_completed_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='points',
            field=models.PositiveIntegerField(blank=True, default=1, null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Баллы'),
        ),
    ]
